on:
  push:
    branches: 
      - deploy

name: Deploy to Amazon EC2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    
    - name: Poetry export requirements
      run: ~/.poetry/bin/poetry export -f requirements.txt > requirements.txt
      
    - name: Docker Build and Push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: raccoonhj33/project-omok
        tags: latest

    - name: Make pem file
      run: echo ${{ secrets.OMOK_PEM }} > t.pem && chmod 400 t.pem
    - name: Excute docker-compose
      run: ssh -o StrictHostKeyChecking=no -i ./t.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} -C ./deploy.sh
